### ISSUE TITLE
Preliminary decision on Class Functionality

### ISSUE THREAD

**Issue by JaiSh12345** [JaiSh12345/JavaLibrary#5]
We have till Monday to discuss it. Let us think over the weekend.

**Comment by praveshishere-old** [comment]
I can't understand Jaideep, what do we need to do, and are you really sure that class list is complete

**Comment by JaiSh12345** [comment]
We have our list of classes now and it is quite extensive, right?
No need for any more classes at the moment.
Now we need to just describe each class' data members and methods, which we are already doing in the other file. We can discuss it on Monday once that document is preliminarily complete.

**Comment by JaiSh12345** [comment]
I am creating a template for a flowchart which I will soon upload here.
We will use that to visually describe our Library.
